### ISSUE TITLE
Getting Trust anchor for certification path not found error

### ISSUE THREAD

**Issue by initiuminc1** [eurbon/Paho-MQTT-Android-TCP-TLS-WSS-Example#2]
MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

This happens on  android 6

**Comment by eurbon** [comment]
@initiuminc1  this problem has to do with the way you are opening a resource file (in this case a raw certificate file). 

Lookup how raw cert file can be opened in marshmallow and then just handle the file opening use case for marshmallow in a different way.

**Comment by rafaelje** [comment]
@initiuminc1 I got the same error when trying to do in my own environment, to solve the problem I need to create my own certification on our server maybe these commands works for you too:

```
> openssl req -config openssl.cnf -new -x509 -extensions v3_ca -days 3650 -keyout private/caserver.key -out certs/caserver.crt
> openssl req -config openssl.cnf -new -nodes -keyout private/client.key -out client.csr -days 1095
> openssl ca -config openssl.cnf -cert certs/caserver.crt -policy policy_anything -out certs/client.crt -infiles csr/client.csr
> openssl pkcs12 -export -clcerts -in certs/client.crt  -inkey private/client.key -out p12client.p12
```

after that add this certification on the raw folder and change the reference on the code
