### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by aldock** [eurbon/Paho-MQTT-Android-TCP-TLS-WSS-Example#4]
Hi eurbon, i´m trying the code but even tcp is not connecting. Could youhelp?

**Comment by eurbon** [comment]
This is more likely related to your device settings

**Comment by Anvay** [comment]
I am getting an error. java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. I am using getAssets() to open by certificate files from.

Any idea?

**Comment by 6d7a** [comment]
Did you add <service android:name="org.eclipse.paho.android.service.MqttService"/> to your AndroidManifest?
